### ISSUE TITLE
Add functionality from Advanced CLIP encoders

### ISSUE THREAD

**Issue by DeInfernal** [asagi4/comfyui-prompt-control#3]
I absolutely love how you made this node, but I miss functionality from [Advanced CLIP Text Encode](https://github.com/BlenderNeko/ComfyUI_ADV_CLIP_emb). They both currently create CONDITIONING output with different results. Can you somehow merge your prompt control with weight control, to get the best of both worlds? Thank you.

**Comment by asagi4** [comment]
I had an experiment to allow "calling out" to arbitrary other nodes, but that didn't work so well (too hacky). It's probably not too difficult to implement a node around the common encoding function, so I can take a look later.

**Comment by asagi4** [comment]
Well, that wasn't difficult at all.

I didn't really test them beyond making sure that it seems to affect generations, so I'm not sure if the integration is completely correct. If it differs from what the actual nodes produce, you can open another issue about that.

**Comment by DeInfernal** [comment]
Well, it throws an error.

```
Traceback (most recent call last):
  File "D:\StableDiffusion\ComfyUI\execution.py", line 145, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\StableDiffusion\ComfyUI\execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\StableDiffusion\ComfyUI\execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\StableDiffusion\ComfyUI\custom_nodes\comfyui-prompt-control\prompt_control\node_clip.py", line 148, in apply
    r = (control_to_clip_common(self, clip, prompt_schedule),)
  File "D:\StableDiffusion\ComfyUI\custom_nodes\comfyui-prompt-control\prompt_control\node_clip.py", line 315, in control_to_clip_common
    cond = encode(c)
  File "D:\StableDiffusion\ComfyUI\custom_nodes\comfyui-prompt-control\prompt_control\node_clip.py", line 303, in encode
    cond_cache[cachekey] = do_encode(clip, prompt)
  File "D:\StableDiffusion\ComfyUI\custom_nodes\comfyui-prompt-control\prompt_control\node_clip.py", line 221, in do_encode
    cond, pooled = encode_prompt(clip, prompts[0], style, normalization)
  File "D:\StableDiffusion\ComfyUI\custom_nodes\comfyui-prompt-control\prompt_control\node_clip.py", line 204, in encode_prompt
    return advanced_encode_from_tokens(
TypeError: advanced_encode_from_tokens() got an unexpected keyword argument 'return_pooled'
```

I used this basic workflow to test it: https://hastebin.pw/dmiIGPJqDs

**Comment by DeInfernal** [comment]
Shit, my bad. Haven't pulled latest version of Advanced. Sorry.
