### ISSUE TITLE
[BUG] in the example workflow

### ISSUE THREAD

**Issue by miasik** [asagi4/comfyui-prompt-control#60]
Could you please review your example https://github.com/asagi4/comfyui-prompt-control/blob/master/workflows/example.json?raw=1
I see "PCApplySettings" is not connected
As I understand it has to be connected both to "ScheduleToCond" and "ScheduleToModel"

![изображение](https://github.com/user-attachments/assets/1b1fd862-c15f-4289-9d60-72591826225b)

**Comment by asagi4** [comment]
Huh. Well, I'll fix that at some point.

**Comment by miasik** [comment]
> Huh. Well, I'll fix that at some point.

Also, please, add "PCSplitSampling" to the example because I always get ab error:
```Prompt executed in 0.02 seconds
got prompt
Failed to validate prompt for output 145:
* (prompt):
  - Required input is missing: images
* PreviewImage 145:
  - Required input is missing: images
Output will be ignored
Failed to validate prompt for output 134:
* VAEDecode 133:
  - Required input is missing: samples
Output will be ignored
[ERROR] PromptControl: Exception occurred during callback, unpatching model.
[INFO] PromptControl: Unpatching model
!!! Exception during processing !!! 'start_percent'
Traceback (most recent call last):
  File "g:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "g:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1430, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1397, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-control\prompt_control\hijack.py", line 39, in pc_sample
    r = cb(orig_sampler, is_custom, *args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-control\prompt_control\node_lora.py", line 102, in sampler_cb
    new_args[6] = filter_conds(new_args[6], "positive", start_t, end_t)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-control\prompt_control\node_lora.py", line 72, in filter_conds
    start_at = round(x["start_percent"], 2)
                     ~^^^^^^^^^^^^^^^^^
KeyError: 'start_percent'```
The prompt is:
```STYLE(A1111)
A lonesome feminine biomechanical unit is posing for an outdoor shot at sunset wearing engraved and jewel-encrusted [Rome legionary styled:futuristic:0.25] dress with subsurface scattering```

**Comment by miasik** [comment]
I've finally managed to properly connect "PCSplitSampling" but I also found an incompatibility with some "ComfyUI-Impact-Pack" nodes:
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/751

**Comment by asagi4** [comment]
I redid the example workflow. I removed some of the more obscure features from it but added eg. custom mask usage.

**Comment by miasik** [comment]
> I redid the example workflow. I removed some of the more obscure features from it but added eg. custom mask usage.

I see "PCSplitSampling" right after "Load Checkpoint". Don't I have to place it at exactly before KSampler?

**Comment by asagi4** [comment]
@miasik I'm pretty sure it should work in either position since all it does is set a flag in `model_options`
