### ISSUE TITLE
[BUG] ScheduleToCond: Sizes of tensors must match except in dimension 2. Expected size 154 but got size 231 for tensor number 1 in the list.

### ISSUE THREAD

**Issue by miasik** [asagi4/comfyui-prompt-control#64]
The bug occurs when I use different prompts for clip_l and clip_g.

Here is my raw prompt as it is generated/combined before passing to "PromptToSchedule"

`"STYLE(A1111) CLIP_L(A sacred moonlit tropical paradise offers a peaceful escape from the harsh realities of the world. The air shimmers with mana as it dances among the reflections in a steaming hot spring on a warm night. A beautiful Black woman with a radiant smile and bright, sparkling eyes, her natural hair styled in an effortless way, poses as a priestess of the wild.  She wears a delicate embroidered camisole, a short skirt that sits low on her hips, and thigh-high stockings that accentuate her toned physique. )       A sacred moonlit tropical paradise in a brutal world. Mana flows among reflections in the middle of a hot spring night. A playful looking back enlightened black lady with her deep sparkling eyes and natural haircut is posing as a priestess of wild nature. An embroidered camisole, a low-rise mini skirt and thigh highs covers her athletic shapes."`

From the console:
```got prompt
[INFO] PromptControl: Encoded SDXL CLIP_L prompt: A sacred moonlit tropical paradise offers a peaceful escape from the harsh realities of the world. The air shimmers with mana as it dances among the reflections in a steaming hot spring on a warm night. A beautiful Black woman with a radiant smile and bright, sparkling eyes, her natural hair styled in an effortless way, poses as a priestess of the wild.  She wears a delicate embroidered camisole, a short skirt that sits low on her hips, and thigh-high stockings that accentuate her toned physique.



!!! Exception during processing !!! Sizes of tensors must match except in dimension 2. Expected size 154 but got size 231 for tensor number 1 in the list.
Traceback (most recent call last):
  File "g:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "g:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-control\prompt_control\node_clip.py", line 151, in apply
    r = (control_to_clip_common(clip, prompt_schedule),)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-control\prompt_control\node_clip.py", line 692, in control_to_clip_common
    cond = encode(c)
           ^^^^^^^^^
  File "G:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-control\prompt_control\node_clip.py", line 668, in encode
    cond_cache[cachekey] = do_encode(clip, prompt, schedules.defaults, schedules.masks)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-control\prompt_control\node_clip.py", line 588, in do_encode
    cond, pooled = encode_prompt(clip, prompt, style, normalization)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-control\prompt_control\node_clip.py", line 385, in encode_prompt
    return prepareXL(embs_l, embs_g, pooled, 0.5)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb\adv_encode.py", line 239, in prepareXL
    return torch.cat([embs_l * l_w, embs_g * g_w], dim=-1), pooled
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Sizes of tensors must match except in dimension 2. Expected size 154 but got size 231 for tensor number 1 in the list.

Prompt executed in 0.36 seconds```

**Comment by asagi4** [comment]
Hmm, this is a problem with the padding code. Should be a quick fix.

**Comment by asagi4** [comment]
Try with the latest commit; there was a bug and it was using the clip l prompt for padding which won't work if its length is misaligned with the clip g prompt.

**Comment by miasik** [comment]
It works now, thanks!
