### ISSUE TITLE
[BUG] Import Failed.

### ISSUE THREAD

**Issue by Takeover713** [asagi4/comfyui-prompt-control#68]
Hello im using the comfyui app for windows. The comfy ui app updated today. 
Then i searched for updates with the manager and it said prompt control had an update. 
i updated it now im getting this error message. 
says Import Failed.
![comfyerror](https://github.com/user-attachments/assets/90ae7bd8-8928-4413-aac1-f5f8a2a44e75)

**Comment by asagi4** [comment]
Hmm, if you're using a released version of ComfyUI, it might not have hooks yet. I'll add a quick workaround for that.

**Comment by asagi4** [comment]
Also, that error message looks very weird. Somehow you seem to have ComfyUI and the custom nodes in a different directory? How does that work?

What version of ComfyUI do you have installed in D:\ComfyUI\ComfyUI\?

I don't have Windows myself so unfortunately I have no way of debugging issues with the Electron app.

**Comment by Takeover713** [comment]
Hi, thanks for the reply. im using the Comfyui desktop app(windows) i think it may be in closed beta. 
https://www.comfy.org/ 
https://github.com/Comfy-Org/desktop
When installing custom nodes it usually puts them in my D drive.
but when theres an update for the comfyUI app. it reinstalled them in my C drive. not sure why. 
i tried reinstalling Prompt control on my C drive also where the other custom nodes are. it gave me the same error.
![comfyinfo](https://github.com/user-attachments/assets/14b0f3e6-e9ac-41a2-bf21-86102af339ba)

**Comment by Neytiri7** [comment]
```
Traceback (most recent call last):
  File "C:\Users\Diana\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\nodes.py", line 2026, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "W:\SynologyDrive\ComfyUI_D\ComfyUI\custom_nodes/ComfyUI-Advanced-ControlNet\__init__.py", line 1, in <module>
    from .adv_control.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "W:\SynologyDrive\ComfyUI_D\ComfyUI\custom_nodes/ComfyUI-Advanced-ControlNet\adv_control\nodes.py", line 3, in <module>
    from .nodes_main import (ControlNetLoaderAdvanced, DiffControlNetLoaderAdvanced,
  File "W:\SynologyDrive\ComfyUI_D\ComfyUI\custom_nodes/ComfyUI-Advanced-ControlNet\adv_control\nodes_main.py", line 6, in <module>
    from .control import load_controlnet, convert_to_advanced, is_advanced_controlnet, is_sd3_advanced_controlnet
  File "W:\SynologyDrive\ComfyUI_D\ComfyUI\custom_nodes/ComfyUI-Advanced-ControlNet\adv_control\control.py", line 11, in <module>
    from comfy.controlnet import ControlBase, ControlNet, ControlNetSD35, ControlLora, T2IAdapter, StrengthType
ImportError: cannot import name 'ControlNetSD35' from 'comfy.controlnet' (C:\Users\Diana\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\controlnet.py)

Cannot import W:\SynologyDrive\ComfyUI_D\ComfyUI\custom_nodes/ComfyUI-Advanced-ControlNet module for custom nodes: cannot import name 'ControlNetSD35' from 'comfy.controlnet' (C:\Users\Diana\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy\controlnet.py)
Use STYLE(weight_interpretation, normalization) at the start of a prompt to use advanced encodings
Weight interpretations available: comfy,A1111,compel,comfy++,down_weight,perp
Normalization types available: none,mean,length,length+mean
Traceback (most recent call last):
  File "C:\Users\Diana\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\nodes.py", line 2026, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "W:\SynologyDrive\ComfyUI_D\ComfyUI\custom_nodes/comfyui-prompt-control\__init__.py", line 16, in <module>
    from .prompt_control.node_hooks import PCLoraHooksFromSchedule, PCEncodeSchedule
  File "W:\SynologyDrive\ComfyUI_D\ComfyUI\custom_nodes/comfyui-prompt-control\prompt_control\node_hooks.py", line 7, in <module>
    import comfy.hooks
ModuleNotFoundError: No module named 'comfy.hooks'
```

**Comment by asagi4** [comment]
Looking at this, it seems that ComfyUI desktop v0.3.26 is what you need; your version is too old:
https://github.com/Comfy-Org/desktop/commits/main

**Comment by asagi4** [comment]
I pushed a workaround that allows the extension to work on older ComfyUI. However, you will not have the new nodes until you update.

**Comment by Takeover713** [comment]
Thank you. yea its working now. greatly appreciate it. i will wait for them to push the update out. i dont see any update button or update bat files in the directories. Thank you for the amazing custom node.

**Comment by asagi4** [comment]
Good to hear that it works. You're welcome!
